spring:
  profiles:
    group:
      default: "common,error"
      local: "default,local"
      dev: "default,develop"
      test: "default,test"
      stag: "default,staging"
      prod: "default,product"
    active: local

  config:
    import: optional:file:.env[.properties] # .env 파일 읽기 설정

---

spring:
  config:
    activate:
      on-profile: common

  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      fail-on-empty-beans: false
    mapper:
      default-view-inclusion: true

  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

  main:
    web-application-type: servlet

server:
  port: ${SERVER_PORT} # 환경 변수 사용
  forward-headers-strategy: framework

logging:
  level:
    root: info

jwt:
  secret: ${JWT_SECRET} # 환경 변수 사용
  expiration-time: ${JWT_EXPIRATION_TIME} # 환경 변수 사용
  refresh-expiration-time: ${JWT_REFRESH_EXPIRATION_TIME} # 환경 변수 사용

springdoc:
  swagger-ui:
    path: /swagger
    url: /docs/openapi3.yaml
    operations-sorter: alpha
  api-docs:
    path: /api-docs
  show-login-endpoint: false

swagger:
  local:
    url: ${SWAGGER_LOCAL_URL} # 환경 변수 사용
  external:
    url: ${SWAGGER_EXTERNAL_URL} # 환경 변수 사용

---

spring:
  config:
    activate:
      on-profile: local

  data:
    mongodb:
      database: ${MONGODB_DATABASE} # 환경 변수 사용
      uri: ${MONGODB_URI} # 환경 변수 사용
